# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

    boot.loader.grub.device = "/dev/sda"; # or "nodev" for efi only
    #boot.loader.grub.enableCryptodisk = true;

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "firewire_ohci" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
    boot.kernelModules = [ "kvm-intel" "wl" "fbcon" "snd-seq" "snd-rawmidi"
        "tun" "virtio" "fuse" 
    ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

    boot.initrd.luks.devices = [
    { name = "Root"; device = "/dev/disk/by-uuid/d4f9c7b0-7355-4fba-b661-4b78ecf28e99"; preLVM = true;
      keyFile = "/dev/disk/by-partuuid/ec1a1a23-02";
    }
    ];

  fileSystems."/" =
    { device = "/dev/mapper/Root-root";
      fsType = "ext4";
    };

    fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1eeef722-9abc-42b7-8ed1-3d29de92773c";
        fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/mapper/Root-swap"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = "ondemand";
}
