# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

    boot.loader.grub.device = "/dev/sda"; # or "nodev" for efi only
    #boot.loader.grub.enableCryptodisk = true;

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "firewire_ohci" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
    boot.kernelModules = [ "kvm-intel" "fbcon" "snd-seq" "snd-rawmidi"
        "tun" "virtio" "fuse"
    ];
  boot.extraModulePackages = [ ];

    boot.initrd.luks.devices = [
    { name = "Root"; device = "/dev/disk/by-uuid/da0fde73-4942-4fee-bcbb-658e8760a0d5"; preLVM = true;
      keyFile = "/dev/disk/by-partuuid/2994f81d-02";
    }
    ];

  fileSystems."/" =
    { device = "/dev/mapper/Root-root";
      fsType = "ext4";
    };

    fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/cfc77947-c000-4549-8385-54313c624665";
        fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/mapper/Root-swap"; }
    ];

  nix.maxJobs = lib.mkDefault 1;
  powerManagement.cpuFreqGovernor = "ondemand";
  networking.enableIntel2200BGFirmware = true;
}
